Bump Faker package back down to ^8 to fix broken tests
Faker is a dependency of another package, for some reason in the previous
package upgrades faker was upgraded from ^8 to ^9, which broke tests with
errors like the following:
```
  File "/usr/local/lib/python3.7/site-packages/faker/providers/automotive/__init__.py", line 5, in <module>
    from .. import BaseProvider, ElementsType
ImportError: cannot import name 'ElementsType' from 'faker.providers' (/usr/local/lib/python3.7/site-packages/faker/providers/__init__.py)
```

This commit explicitly adds Faker to bring it back down to version 8.

We may want to figure out a way in the future to remove Faker again from
being added as an explicit dev dependency and allow Poetry to manage the depenency
tree.  I wasn't sure how to do that right now, though.